name: Publish individual NuGet package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: |
          dotnet restore src/Tools.sln
          dotnet build src/Tools.sln --configuration Release --no-restore

      - name: Pack Tools.Swift.Connector
        run: dotnet pack src/Tools.Swift.Connector/Tools.Swift.Connector.csproj --configuration Release --no-build --output ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

 